
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: saidit_development

test:
  <<: *default
  database: saidit_test

production:
  <<: *default
  database: saidit_production
  username: saidit
  password: <%= ENV['SAIDIT_DATABASE_PASSWORD'] %>
