# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee58c02a62d155832cd1e0590d93d7c4808cf7cc007a94af048b7bf7cd1f0902d8ee62833daf9b6d40dbc1fb038c06439e168ecad94ad1fcf1cb03986c31271

test:
  secret_key_base: 31a616a38482dcb16aacb3ee03f7e360a1ae02bd9dd93df55803c0799aea93cb810b978df32edaab80d5090c50733d56be4e98c96ad0cb5816b35cf2448ae099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
